# .bashrc

PS1='\[\033[0;36m\][\u@\h \w]\$ \[\033[0m\]'

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias ggrep='grep -irnI --exclude-dir=".svn" --exclude-dir=".git" --exclude="*.cmd" ./ -e'
alias cgrep='find . -name "*.[ch]" -o -name "*.cpp" -o -name "*.asp" -o -name "*.js" -o -name "*.css" -o -name "Makefile" -o -name "cy_configure" | xargs grep -inI ./ -e'
alias svnex="svn pg svn:externals"

# dev
_dev_path="/work/develop"
alias q="sh $_dev_path/shellScript/stock.sh"
alias stock="python $_dev_path/python/htmlparser/kStock_thread.py"
alias check="python $_dev_path/python/htmlparser/check50List.py"
alias initgit="$_dev_path/shellScript/initgit.sh"
alias re-ssh="$_dev_path/shellScript/re-ssh.sh"
alias getip="$_dev_path/shellScript/get_ip.sh"
alias geturl="$_dev_path/shellScript/get_curl_url.sh"

# work
alias list="$_dev_path/shellScript/common_login.sh"
alias list-s="$_dev_path/shellScript/common_login.sh -s"
alias tt="$_dev_path/shellScript/login.sh -s"
alias ss="$_dev_path/shellScript/login.sh"
alias ss100="$_dev_path/shellScript/login.sh -I 100"
alias ss104="$_dev_path/shellScript/login.sh -I 104"
alias ssaws="ssh ubuntu@ec2-54-199-171-173.ap-northeast-1.compute.amazonaws.com"
alias con="$_dev_path/shellScript/login.sh -s -u console"
alias upgrade="$_dev_path/shellScript/login.sh -a upgrade"
alias upgradew="$_dev_path/shellScript/login.sh -a upgrade -t wms -I 104"
alias debug="$_dev_path/shellScript/login.sh -u root -a debug -d"
alias casetest="$_dev_path/shellScript/caseTest.sh"
alias setip="$_dev_path/tcl/setup_ip.tcl"
alias gittree="git log --graph --oneline --all --decorate=short"
alias gitrebase="git rebase verify^ verify --onto"

alias war3="wine /data/Game/WarcraftIII/war3.exe -opengl -windows"

# tools
alias mdns="/data/tool/mDNS/mDNSResponder-333.10/mDNSPosix/build/prod/mDNSIdentify cisco00013.local"
alias noip="/data/tool/noip-2.1.9-1/noip2 -c /data/tool/noip-2.1.9-1/no-ip2.conf"


source $_dev_path/shellScript/bashDirB
source /etc/bash_completion.d/git
#source /usr/share/git-core/contrib/completion/git-prompt.sh for Fedora 18+
#source /etc/bash_completion.d/git for RedHat/CentOS or Fedora 16-17

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions
